CREATE TABLE IF NOT EXISTS COMMENT (
	COMMENT_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	PARENT_ID BIGINT,
	AUTHOR_ID BIGINT NOT NULL,
	ARTICLE_ID BIGINT NOT NULL,
	CONTENT VARCHAR(255),
	CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
	IS_DELETED BIT(1) NOT NULL DEFAULT B'0'
);