CREATE TABLE IF NOT EXISTS COMMENT (
	COMMENT_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	AUTHOR_ID BIGINT NOT NULL,
	ARTICLE_ID BIGINT NOT NULL,
	CONTENT VARCHAR(255),
	LIKE_COUNT BIGINT DEFAULT 0,
	CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);